#!/bin/bash
##########################################################
#     Automatically generated by the PandA framework     #
##########################################################

# Synthesis script for COMPONENT: test

# STEP: vivado_flow
cd /mnt/c/Users/marco/Desktop/COaT_project/Tests/FromTaffo_test3
ulimit -s 131072; vivado -mode batch -nojournal -nolog -source /mnt/c/Users/marco/Desktop/COaT_project/Tests/FromTaffo_test3/HLS_output//Synthesis/vivado_flow_0/vivado.tcl


