#!/bin/bash
##########################################################
#     Automatically generated by the PandA framework     #
##########################################################

# Synthesis script for COMPONENT: main

# STEP: vivado_flow
cd /mnt/c/Users/marco/Desktop/COaT_project/Tests/SimpleTaffoTest
ulimit -s 131072; vivado -mode batch -nojournal -nolog -source /mnt/c/Users/marco/Desktop/COaT_project/Tests/SimpleTaffoTest/HLS_output//Synthesis/vivado_flow/vivado.tcl


